### ISSUE TITLE
maybe Math is wrong?

### ISSUE THREAD

**Issue by FKrauss** [runcitadel/dashboard#18]
![Screenshot from 2022-04-25 15-26-03](https://user-images.githubusercontent.com/4820683/165098367-de67bc29-3dd0-4eb0-8dbb-5ab962740428.png)

Hi there,

I installed Citadel yesterday and the Node started syncing. While looking at the progress bar and if you do the calculations it doesn't really add up.

Dashboard says: 10.75%
But if you divide: 369,259/733,469, you get something  around 50.3%

Which is right? 
Either way, one needs to be fixed.

Thanks!

**Comment by pwltr** [comment]
The percentage number you're seeing here is what's reported by bitcoind as verification progress which is an estimate based on the number of transactions it knows about from the network. Since blocks were mostly empty at the start this is accurate as the verification of blocks is what's actually taking time. You might even see it go down at some point as it sees blocks filling up and adjusts estimation.
But I agree this could be confusing for new users and it would be a good idea to add a small info popup somewhere with an explanation.

**Comment by WilliamConnatser** [comment]
I think it would be more straightforward if it was split into two separate metrics: blocks synced and blocks verified.

**Comment by AaronDewes** [comment]
That would still be confusing/wrong because the amount of blocks loaded and verified is the same. Also, newer blocks are bigger and take longer to verify.

**Comment by FKrauss** [comment]
Maybe the ideal solution is not about changing the metric, but explaining what it is (or even linking to an article that goes in depth)

**Comment by WilliamConnatser** [comment]
While I have come to agree with the initial reasoning of this issue, I believe that the dashboard UI no longer shows a count of blocks so this issue may be outdated. If everyone else agrees, then we can possibly close this issue because it is no longer applicable?

**Comment by pwltr** [comment]
> While I have come to agree with the initial reasoning of this issue, I believe that the dashboard UI no longer shows a count of blocks so this issue may be outdated. If everyone else agrees, then we can possibly close this issue because it is no longer applicable?

I believe that is only shown when you're behind 1 or 2 blocks, i.e. during IBD. See PR https://github.com/runcitadel/dashboard/pull/48
